# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-23 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180123_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='sport',
            field=models.CharField(choices=[('FB', 'Football'), ('RB', 'Rugby'), ('AF', 'American Football')], max_length=10),
        ),
    ]
