# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-23 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180123_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='sport',
            field=models.CharField(choices=[('Football', 'Football'), ('Rugby', 'Rugby'), ('American Football', 'American Football')], max_length=20),
        ),
    ]
