# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180123_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_url', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
