# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_addtodatabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddToDatabase',
        ),
    ]
